### ISSUE TITLE
Cross compiling?

### ISSUE THREAD

**Issue by maddie** [goburrow/serial#3]
`github.com/goburrow/modbus` depends on this library, and when I try to run:

`GOOS=windows GOARCH=amd64 go build -o hello.exe main.go`

It says:
```
# github.com/goburrow/serial
/path/to/gopath/src/github.com/goburrow/serial/serial.go:43: undefined: New
```

So it's currently not possible to cross compile? (Linux host, Windows binary)

And a side question that doesn't really deserve another issue -- under Linux we can use `/dev/ttyS0` as the address, what if in Windows? Just use `COM1`?

Thanks a lot for your work!

**Comment by nqv** [comment]
Thanks for your report, I haven't tried cross compiling yet as it currently requires CGO under Windows unfortunately. I'm going to get rid of it.
Try `COM1` as the address, if it doesn't work, you might give this a shot: `\\.\COM1`. (note that the string have to be escaped and it will be `"\\\\.\\COM22"`.

**Comment by maddie** [comment]
Thanks for your response.

I'm aware that compiling on Windows it tells me gcc is not found, that's why I was trying to cross compile in a Linux host.

For now I'll try to set up the Windows environment and compile, thanks again for your great work!

**Comment by nqv** [comment]
You still need cgo in Windows, please refer here for installation: https://github.com/golang/go/wiki/cgo (as mentioned in README).
Removing cgo is in progress, it will make building in Windows much less painful :)

**Comment by maddie** [comment]
Alright, thanks!

**Comment by nqv** [comment]
@maddie I've just replace cgo dependency with its generated files. Please let me know if you find any issues.
Thanks.

**Comment by maddie** [comment]
Hi there!

Compiling for `GOOS=windows GOARCH=amd64` is now successful under Linux.

However compiling for `GOARCH=386` fails with following message:

```
COOS=windows GOARCH=386 go build -o hello.exe main.go                                                  [16:20:17]
# github.com/goburrow/serial
/path/to/gopath/src/github.com/goburrow/serial/serial_darwin.go:179: cannot use flag (type uint64) as type uint32 in assignment
/path/to/gopath/src/github.com/goburrow/serial/serial_darwin.go:181: cannot use flag (type uint64) as type uint32 in assignment
/path/to/gopath/src/github.com/goburrow/serial/serial_darwin.go:192: invalid operation: termios.Cflag |= flag (mismatched types uint32 and uint64)
```

Thank you!

**Comment by maddie** [comment]
I guess it could be related to the OS (since OS X are all 64-bit now), so if it's not an easy fix, building on Linux would suffice.

Thank you!

**Comment by nqv** [comment]
Not sure if OS X can be used on 386 :P
