### ISSUE TITLE
undefined: syscall.Termios

### ISSUE THREAD

**Issue by fsyxhua** [goburrow/serial#4]
$ go get -u -v github.com/goburrow/modbus
github.com/goburrow/modbus (download)
github.com/goburrow/serial (download)
github.com/goburrow/serial
\#  github.com/goburrow/serial
..\github.com\goburrow\serial\serial_posix.go:13: undefined: syscall.Termios
..\github.com\goburrow\serial\serial_windows.go:8: port redeclared in this block
        previous declaration at ..\github.com\goburrow\serial\serial_posix.go:11
..\github.com\goburrow\serial\serial_windows.go:13: New redeclared in this block
        previous declaration at ..\github.com\goburrow\serial\serial_posix.go:19
..\github.com\goburrow\serial\serial_windows.go:20: (\*port).Open redeclared in t                                                                                               his block
        previous declaration at ..\github.com\goburrow\serial\serial_posix.go:24
..\github.com\goburrow\serial\serial_windows.go:45: (\*port).Close redeclared in                                                                                                this block
        previous declaration at ..\github.com\goburrow\serial\serial_posix.go:48
..\github.com\goburrow\serial\serial_windows.go:56: (\*port).Read redeclared in t                                                                                               his block
        previous declaration at ..\github.com\goburrow\serial\serial_posix.go:61
..\github.com\goburrow\serial\serial_windows.go:70: (\*port).Write redeclared in                                                                                                this block
        previous declaration at ..\github.com\goburrow\serial\serial_posix.go:92

**Comment by nqv** [comment]
hmm, what is OS and arch of your system?

**Comment by nguyenthenguyen** [comment]
Me too!. I'm on windows 64bit. I try on go 1.6 and 1.5 are errors
![untitled](https://cloud.githubusercontent.com/assets/8535630/14747879/a7e333f4-086b-11e6-85f3-50fb76e31d7f.png)

**Comment by nqv** [comment]
The issue should be fixed now. Thanks for your report.
