### ISSUE TITLE
Cant cross compile from Linux to Freebsd

### ISSUE THREAD

**Issue by Tuzkov** [goburrow/serial#7]
Hello!
I use github.com/goburrow/modbus in my project and when I try to compile project to FreeBSD -
```
# github.com/goburrow/serial
../github.com/goburrow/serial/serial.go:43: undefined: New
```
Can you help me please?

Thank you for help!

**Comment by nqv** [comment]
I've added an initial support for BSD. You should be able to cross compile to FreeBSD now, but I haven't checked if it will work properly as I never use BSD, sorry.
Anyway, I will make the modbus library the ability to choose other serial libraries -  which might fully support all features you need.

**Comment by Tuzkov** [comment]
Thank you very much!
It helps.
